# Generated by Django 5.2.3 on 2025-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('FUEL', 'Fuel'), ('GROCERY', 'Grocery'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
