# Generated by Django 5.2.3 on 2025-06-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_expense_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
